version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - echo Installing... Running npm install.
      - npm install
  pre_build:
    commands:
      - echo pre_build...
  build:
    commands:
      - echo Testing... Running npm test.
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`.
artifacts:
  files:
    - '**/*'